parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(DATABASE_URL)%'
        types:
            userId: Ramsey\Uuid\Doctrine\UuidType
            companyId: Ramsey\Uuid\Doctrine\UuidType
            productId: Ramsey\Uuid\Doctrine\UuidType
            orderId: Ramsey\Uuid\Doctrine\UuidType
            orderItemId: Ramsey\Uuid\Doctrine\UuidType
            shipmentId: Ramsey\Uuid\Doctrine\UuidType
            eventAwareId: Ramsey\Uuid\Doctrine\UuidType
            event: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            json: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/orm/domain'
                prefix: 'App\Domain'
                alias: Domain
            Projections:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/mapping/orm/infrastructure'
                prefix: 'App\Infrastructure'
                alias: Infrastructure
