# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    default_bus: command
    method_inflector: tactician.handler.method_name_inflector.invoke
    commandbus:
        default:
            middleware:
                - tactician.middleware.logger
                - App\Infrastructure\Common\Bus\Middleware\EventDispatcherMiddleware
                - tactician.middleware.doctrine
                - App\Infrastructure\Common\Bus\Middleware\EventPublisherMiddleware
                - App\Infrastructure\Common\Bus\Middleware\EventStoreMiddleware
                - tactician.middleware.command_handler
        query:
            middleware:
                - tactician.commandbus.query.middleware.command_handler
        command:
            middleware:
                - tactician.commandbus.command.middleware.command_handler
