App\Domain\Warehouse\Model\Order:
    type: entity
    table: product_order
    repositoryClass: App\Infrastructure\Warehouse\Repository\OrderRepository
    id:
        uuid:
            type: orderId
            nullable: false

    fields:
        orderNumber:
            type: string
            unique: true
        address:
            type: text
        state:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime

    oneToOne:
        shipment:
            targetEntity: App\Domain\Warehouse\Model\Shipment
            joinColumn:
                name: fk_shipment
                referencedColumnName: uuid
                nullable: true
                onDelete: CASCADE
            cascade:
                - all

    manyToOne:
        company:
            targetEntity: App\Domain\Company\Model\Company
            joinColumn:
                name: fk_company
                referencedColumnName: uuid
                nullable: false
                onDelete: CASCADE
            cascade:
                - all
        user:
            targetEntity: App\Domain\User\Model\User
            joinColumn:
                name: fk_user
                referencedColumnName: uuid
                nullable: false
                onDelete: CASCADE
            cascade:
                - all

    oneToMany:
        items:
            targetEntity: App\Domain\Warehouse\Model\OrderItem
            mappedBy: order
            cascade:
                - all

    lifecycleCallbacks: {  }
